=== RegardsOss/regards-backend/rs-dataprovider/acquisition/acquisition-plugins-ssalto/src/main/resources/ssalto/domain/plugins/impl/tools/schemas_plugins.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 sp1 U (http://www.xmlspy.com) by CS SYSTEMES D'INFORMATION (CS SYSTEMES D'INFORMATION) -->
<!--
 $Id$

 HISTORIQUE

 VERSION : 5.4.1 : DM : SIPNG-DM-0151-CN : 11/07/2014 : Prise en compte des modifications du CNES sur les projets SERAD et COROT.
 
 VERSION : 5.4 : FA : SIPNG-FA-CS-52 : 18/11/2013 : ajout de minOccurs="0"
 
 VERSION : 2011/07/13 : 1.6 : CS
 DM-ID : SIPNG-DM-0070-CN : 2011/06/13 : Amelioration des perf. Plus de mots reserves Oracle comme nom d'attributs. Changer OPTION par PRODUCT_OPTION 

 VERSION : 2009/05/18 : 1.3 : CS
 DM-ID : SIPNG-DM-0060-CN : 2009/07/01 : creation

 FIN-HISTORIQUE
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="PLUGIN_CONFIGURATION">
		<xs:annotation>
			<xs:documentation>Root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="fileNamePattern" type="xs:string">
					<xs:annotation>
						<xs:documentation>file name pattern containing all catch groups to get the required attributes.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:choice maxOccurs="unbounded">
					<xs:element name="compositeAttribute">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="name">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="TIME_PERIOD"/>
											<xs:enumeration value="ORBIT_RANGE"/>
											<xs:enumeration value="CYCLE_RANGE"/>
											<xs:enumeration value="GEO_COORDINATES"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:element>
								<xs:element name="order" type="xs:integer"/>
								<xs:choice minOccurs="2" maxOccurs="unbounded">
									<xs:element name="attributeFromName" type="attributeFromNameType">
										<xs:annotation>
											<xs:documentation>attribute read from fileName</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="translatedAttributeFromName" type="translatedAttributeFromNameType">
										<xs:annotation>
											<xs:documentation>attribute translated from a value read on the file name</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="translatedAttributeFromCycleFile" type="attributeFromOtherType">
										<xs:annotation>
											<xs:documentation>attribute translated from another attribute value read at groupNumber using the cycle file.</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="multipleFileFromName" type="multipleFileFromNameType">
										<xs:annotation>
											<xs:documentation>attribute read from multiple file names after unzip operation for example</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="attributeFromOther" type="attributeFromOtherType">
										<xs:annotation>
											<xs:documentation>attribute read from another attribute value</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="fileInfoAttribute" type="fileInfoAttributeType">
										<xs:annotation>
											<xs:documentation>attribute read from the File system information ( size ...)</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="globalAttributeFromCdfFile" type="globalAttributeFromCdfFileType">
										<xs:annotation>
											<xs:documentation>global cdf attribute value</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="variableValueAttributeFromCdfFile" type="variableValueAttributeFromCdfFileType">
										<xs:annotation>
											<xs:documentation>value of an attribute of a variable</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="enumeratedAttributeFromCdfFile" type="enumeratedAttributeFromCdfFileType">
										<xs:annotation>
											<xs:documentation>list of all the values of the attribute taken in all variable of the cdf file</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="attributeFromAsciiFile" type="attributeFromAsciiFileType">
										<xs:annotation>
											<xs:documentation>attribute read from an ascii file</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="fixedValueAttribute" type="fixedValueAttributeType">
										<xs:annotation>
											<xs:documentation>attribute with fixed value</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="translatedAttributeFromArcFile" type="translatedAttributeFromArcFileType"/>
								</xs:choice>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:choice>
						<xs:element name="attributeFromName" type="attributeFromNameType">
							<xs:annotation>
								<xs:documentation>attribute read from fileName</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="translatedAttributeFromName" type="translatedAttributeFromNameType">
							<xs:annotation>
								<xs:documentation>attribute translated from a value read on the file name</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="translatedAttributeFromCycleFile" type="attributeFromOtherType">
							<xs:annotation>
								<xs:documentation>attribute translated from another attribute value read at groupNumber using the cycle file.</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="multipleFileFromName" type="multipleFileFromNameType">
							<xs:annotation>
								<xs:documentation>attribute read from multiple file names after unzip operation for example</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="attributeFromOther" type="attributeFromOtherType">
							<xs:annotation>
								<xs:documentation>attribute read from another attribute value</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="fileInfoAttribute" type="fileInfoAttributeType">
							<xs:annotation>
								<xs:documentation>attribute read from the File system information ( size ...)</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="globalAttributeFromCdfFile" type="globalAttributeFromCdfFileType">
							<xs:annotation>
								<xs:documentation>global cdf attribute value</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="variableValueAttributeFromCdfFile" type="variableValueAttributeFromCdfFileType">
							<xs:annotation>
								<xs:documentation>value of an attribute of a variable</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="enumeratedAttributeFromCdfFile" type="enumeratedAttributeFromCdfFileType">
							<xs:annotation>
								<xs:documentation>list of all the values of the attribute taken in all variable of the cdf file</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="attributeFromAsciiFile" type="attributeFromAsciiFileType">
							<xs:annotation>
								<xs:documentation>attribute read from an ascii file</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="fixedValueAttribute" type="fixedValueAttributeType">
							<xs:annotation>
								<xs:documentation>attribute with fixed value</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="translatedAttributeFromArcFile" type="translatedAttributeFromArcFileType"/>
					</xs:choice>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="SpecificationType">
		<xs:sequence>
			<xs:element name="name">
				<xs:annotation>
					<xs:documentation>attribute name, which will be written into descriptor file</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="FILE_SIZE"/>
						<xs:enumeration value="OBJECT_VERSION"/>
						<xs:enumeration value="LATITUDE_MAX"/>
						<xs:enumeration value="PHASE"/>
						<xs:enumeration value="LATITUDE_MIN"/>
						<xs:enumeration value="LONGITUDE_MAX"/>
						<xs:enumeration value="LONGITUDE_MIN"/>
						<xs:enumeration value="ORBIT_MAX"/>
						<xs:enumeration value="ORBIT_MIN"/>
						<xs:enumeration value="PARAMETER"/>
						<xs:enumeration value="PRODUCT_OPTION"/>
						<xs:enumeration value="FILE_CREATION_DATE"/>
						<xs:enumeration value="CYCLE_MAX"/>
						<xs:enumeration value="CYCLE_MIN"/>
						<xs:enumeration value="STOP_DATE"/>
						<xs:enumeration value="START_DATE"/>
						<xs:enumeration value="RADICAL"/>
						<xs:enumeration value="FULL_RUN_CODE"/>
						<xs:enumeration value="RUN_TYPE"/>
						<xs:enumeration value="FOV"/>
						<xs:enumeration value="ASTBKGROUNDID"/>
						<xs:enumeration value="ASTOFFSETID"/>
						<xs:enumeration value="CCDID"/>
						<xs:enumeration value="COROTID"/>
						<xs:enumeration value="EXOMONOCHROMID"/>
						<xs:enumeration value="HALFCCDID"/>
						<xs:enumeration value="MASKID"/>
						<xs:enumeration value="TPLID"/>
						<xs:enumeration value="WINID"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="valueType">
				<xs:annotation>
					<xs:documentation>type of value ( Date, Integer,String...)</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="STRING"/>
						<xs:enumeration value="DATE"/>
						<xs:enumeration value="INTEGER"/>
						<xs:enumeration value="DATE_TIME"/>
						<xs:enumeration value="REAL"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="order" type="xs:int" minOccurs="0">
				<xs:annotation>
					<xs:documentation>ordering attribute treatment</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="formatRead" minOccurs="0">
				<xs:annotation>
					<xs:documentation>value format read into file or file name</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="calculationClass" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>classe de transformation de la valeur, par exemple transformation des longitude, ou diminution de la precision d'un nombre</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="defaultValue" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>valeur par defaut si le finder n'est pas capable de renvoyer une valeur</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="unzipBefore" type="xs:boolean" minOccurs="0">
				<xs:annotation>
					<xs:documentation>indique si l'on doit dezipper le fichier avant de pouvoir traiter l'attribut</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="compressionType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>indique le type de compression du fichier Z,ZIP,GZIP, TAR</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="ZIP"/>
						<xs:enumeration value="Z"/>
						<xs:enumeration value="GZIP"/>
						<xs:enumeration value="TAR"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="attributeFromNameType">
		<xs:sequence>
			<xs:element name="groupNumber" type="xs:int" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>catch group number</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="unzipBefore" type="xs:boolean" minOccurs="0">
				<xs:annotation>
					<xs:documentation>indique si l'on doit dezipper le fichier avant de pouvoir traiter l'attribut</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="specification" type="SpecificationType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>specification of the attribute</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="translatedAttributeFromNameType">
		<xs:sequence>
			<xs:element name="groupNumber" type="xs:int" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>catch group number</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="translationFilePath" type="xs:string">
				<xs:annotation>
					<xs:documentation>translation file path</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="specification" type="SpecificationType">
				<xs:annotation>
					<xs:documentation>specification of the attribute</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="multipleFileFromNameType">
		<xs:sequence>
			<xs:element name="fileInZipNamePattern" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>pattern representing the file names into the zip archive. </xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="groupNumber" type="xs:int" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>catch group number</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="calculus">
				<xs:annotation>
					<xs:documentation>calculus method to get the value ( max, avg, min...)</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="min"/>
						<xs:enumeration value="max"/>
						<xs:enumeration value="first"/>
						<xs:enumeration value="last"/>
						<xs:enumeration value="average"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="specification" type="SpecificationType">
				<xs:annotation>
					<xs:documentation>specification of the attribute</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="attributeFromOtherType">
		<xs:sequence>
			<xs:element name="otherAttributeName" type="xs:string" minOccurs="0"/>
			<xs:element name="groupNumber" type="xs:int" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>catch group number</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="specification" type="SpecificationType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>specification of the attribute</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="fileInfoAttributeType">
		<xs:sequence>
			<xs:element name="fileInformation">
				<xs:annotation>
					<xs:documentation>the name of the information to read</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="FILE_SIZE"/>
						<xs:enumeration value="LAST_MODIFICATION_DATE"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="specification" type="SpecificationType">
				<xs:annotation>
					<xs:documentation>specification of the attribute</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="globalAttributeFromCdfFileType">
		<xs:sequence>
			<xs:element name="attributeName" type="xs:string">
				<xs:annotation>
					<xs:documentation>name of the global attribute</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="specification" type="SpecificationType">
				<xs:annotation>
					<xs:documentation>specification of the attribute</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="variableValueAttributeFromCdfFileType">
		<xs:sequence>
			<xs:element name="variableName" type="xs:string">
				<xs:annotation>
					<xs:documentation>variable name</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="calculus">
				<xs:annotation>
					<xs:documentation>calculus method to get the value ( max, avg, min...)</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="min"/>
						<xs:enumeration value="max"/>
						<xs:enumeration value="first"/>
						<xs:enumeration value="last"/>
						<xs:enumeration value="average"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="specification" type="SpecificationType">
				<xs:annotation>
					<xs:documentation>specification of the attribute</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="enumeratedAttributeFromCdfFileType">
		<xs:sequence>
			<xs:element name="attributeName" type="xs:string">
				<xs:annotation>
					<xs:documentation>attribute name</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="except" type="xs:string" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>list of values not to add into the list</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="specification" type="SpecificationType">
				<xs:annotation>
					<xs:documentation>specification of the attribute</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="attributeFromAsciiFileType">
		<xs:sequence>
			<xs:element name="linePattern" type="xs:string">
				<xs:annotation>
					<xs:documentation>pattern representing the line to read and get the value from</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="lineNumber" type="xs:int" minOccurs="0">
				<xs:annotation>
					<xs:documentation>number of the line which contains the value</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="groupNumber" type="xs:string" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>number of the group in the pattern used to catch the value</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="filterPattern" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Filter to select file in multiple file product</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="specification" type="SpecificationType">
				<xs:annotation>
					<xs:documentation>specification of the attribute</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="fixedValueAttributeType">
		<xs:sequence>
			<xs:element name="fixedValue" type="xs:string"/>
			<xs:element name="specification" type="SpecificationType">
				<xs:annotation>
					<xs:documentation>specification of the attribute</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="translatedAttributeFromArcFileType">
		<xs:sequence>
			<xs:element name="groupNumber" type="xs:int" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>catch group number</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="specification" type="SpecificationType">
				<xs:annotation>
					<xs:documentation>specification of the attribute</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== RegardsOss/regards-backend/rs-dataprovider/acquisition/acquisition-plugins-ssalto/src/test/resources/income/plugins/configurations/DA_TC_HY2A_HISTO_FOUS_BORD_PluginConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 $Id$
 
 HISTORIQUE

 VERSION : 5.5 : DM : SIPNG-DM-152-CN : 20/11/2014 : Deplacement des fichiers de configuration des plugins
 

  VERSION : 2011/11/07 : 1.6.1 : CNES CREATION
  DM-ID : SIPNG-DM-0098-CN : 2011/11/07 : creation

 FIN-HISTORIQUE
-->
<PLUGIN_CONFIGURATION xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas_plugins.xsd">
    <fileNamePattern>(H2A_OS([1-2]{1}))_AXXCNE([0-9]{8}_[0-9]{6})(_([0-9]{8}_[0-9]{6})_([0-9]{8}_[0-9]{6}))</fileNamePattern>
    <compositeAttribute>
        <name>TIME_PERIOD</name>
        <order>1</order>
        <attributeFromName>
            <groupNumber>5</groupNumber>
            <specification>
                <name>START_DATE</name>
                <valueType>DATE_TIME</valueType>
                <formatRead>yyyyMMdd_HHmmss</formatRead>
            </specification>
        </attributeFromName>
        <attributeFromName>
            <groupNumber>6</groupNumber>
            <specification>
                <name>STOP_DATE</name>
                <valueType>DATE_TIME</valueType>
                <formatRead>yyyyMMdd_HHmmss</formatRead>
            </specification>
        </attributeFromName>
    </compositeAttribute>
    <translatedAttributeFromName>
        <groupNumber>2</groupNumber>
        <translationFilePath>/HISTOTranslationFile.properties</translationFilePath>
        <specification>
            <name>PRODUCT_OPTION</name>
            <valueType>STRING</valueType>
            <order>2</order>
        </specification>
    </translatedAttributeFromName>
    <attributeFromName>
        <groupNumber>1</groupNumber>
        <specification>
            <name>RADICAL</name>
            <valueType>STRING</valueType>
        </specification>
    </attributeFromName>     
    <attributeFromName>
        <groupNumber>3</groupNumber>
        <specification>
            <name>FILE_CREATION_DATE</name>
            <valueType>DATE_TIME</valueType>
            <order>4</order>
            <formatRead>yyyyMMdd_HHmmss</formatRead>
        </specification>
    </attributeFromName>
</PLUGIN_CONFIGURATION>

=== RegardsOss/regards-backend/rs-dataprovider/acquisition/acquisition-plugins-ssalto/src/test/resources/income/plugins/configurations/DA_TC_HY2A_HISTO_MANOEUVRES_PluginConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 $Id$
 
 HISTORIQUE

 VERSION : 5.5 : DM : SIPNG-DM-152-CN : 20/11/2014 : Deplacement des fichiers de configuration des plugins
 

 VERSION : 2012/05/16 : 1.6.3 : CNES
 FA-ID : SIPNG-FA-0814-CN : 2012/05/16 : plugins fournis par le CNES

 VERSION : 2011/08/15 : 1.6 : CS
 FA-ID : SIPNG-FA-0729-CS : 2011/08/05 : maj fichiers de conf
 
 VERSION : 2010/02/01 : 4.5 : CS
 DM-ID : SIPNG-DM-060-CN : 2010/02/01 : creation

 FIN-HISTORIQUE
-->
<PLUGIN_CONFIGURATION xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas_plugins.xsd">
    <fileNamePattern>(H2A_MAN_AXXCNE(_){0,1})([0-9]{8}_[0-9]{6})(_([0-9]{8}_[0-9]{6})_([0-9]{8}_[0-9]{6}))</fileNamePattern>
    <compositeAttribute>
        <name>TIME_PERIOD</name>
        <order>1</order>
        <attributeFromName>
            <groupNumber>5</groupNumber>
            <specification>
                <name>START_DATE</name>
                <valueType>DATE_TIME</valueType>
                <formatRead>yyyyMMdd_HHmmss</formatRead>
            </specification>
        </attributeFromName>
        <attributeFromName>
            <groupNumber>6</groupNumber>
            <specification>
                <name>STOP_DATE</name>
                <valueType>DATE_TIME</valueType>
                <formatRead>yyyyMMdd_HHmmss</formatRead>
            </specification>
        </attributeFromName>
    </compositeAttribute>
    <fixedValueAttribute>
        <fixedValue>H2A_MAN</fixedValue>
        <specification>
            <name>RADICAL</name>
            <valueType>STRING</valueType>
            <order>3</order>
        </specification>
    </fixedValueAttribute>
    <attributeFromName>
        <groupNumber>3</groupNumber>
        <specification>
            <name>FILE_CREATION_DATE</name>
            <valueType>DATE_TIME</valueType>
            <order>2</order>
            <formatRead>yyyyMMdd_HHmmss</formatRead>
        </specification>
    </attributeFromName>
</PLUGIN_CONFIGURATION>

=== RegardsOss/regards-backend/rs-dataprovider/acquisition/acquisition-plugins-ssalto/src/main/resources/plugins/configurations/DA_TC_JASON2_MNT_POS3_PluginConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<PLUGIN_CONFIGURATION xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas_plugins.xsd">
	<fileNamePattern>(POS3_.*_MNT_)(.*)(\.)(.*)_([0-9]{4}_[0-9]{2}_[0-9]{2}_[0-9]{2}_[0-9]{2}_[0-9]{2})(_EEPROM_)(.*)(\.REF)</fileNamePattern>
	<compositeAttribute>
		<name>TIME_PERIOD</name>
		<order>1</order>
		<attributeFromName>
			<groupNumber>5</groupNumber>
			<specification>
				<name>START_DATE</name>
				<valueType>DATE_TIME</valueType>
				<formatRead>yyyy_MM_dd_HH_mm_ss</formatRead>
			</specification>
		</attributeFromName>
		<attributeFromOther>
			<otherAttributeName>START_DATE</otherAttributeName>
			<specification>
				<name>STOP_DATE</name>
				<valueType>DATE_TIME</valueType>
			</specification>
		</attributeFromOther>
	</compositeAttribute>
	<attributeFromName>
		<groupNumber>7</groupNumber>
		<specification>
			<name>PRODUCT_OPTION</name>
			<valueType>STRING</valueType>
			<order>3</order>
		</specification>
	</attributeFromName>
	<attributeFromName>
		<groupNumber>1</groupNumber>
		<groupNumber>5</groupNumber>
		<groupNumber>6</groupNumber>
		<groupNumber>7</groupNumber>
		<groupNumber>8</groupNumber>
		<specification>
			<name>RADICAL</name>
			<valueType>STRING</valueType>
			<order>4</order>
		</specification>
	</attributeFromName>
	<attributeFromName>
		<groupNumber>2</groupNumber>
		<groupNumber>3</groupNumber>
		<groupNumber>4</groupNumber>
		<specification>
			<name>OBJECT_VERSION</name>
			<valueType>STRING</valueType>
			<order>5</order>
		</specification>
	</attributeFromName>
	<fileInfoAttribute>
		<fileInformation>LAST_MODIFICATION_DATE</fileInformation>
		<specification>
			<name>FILE_CREATION_DATE</name>
			<valueType>DATE_TIME</valueType>
			<order>6</order>
		</specification>
	</fileInfoAttribute>
</PLUGIN_CONFIGURATION>

=== RegardsOss/regards-backend/rs-dataprovider/acquisition/acquisition-plugins-ssalto/src/test/resources/income/plugins/configurations/DA_TC_ENVISAT_HKTM_PluginConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 $Id$

 HISTORIQUE
 
 VERSION : 5.5 : DM : SIPNG-DM-152-CN : 20/11/2014 : Deplacement des fichiers de configuration des plugins

  VERSION : 2009/07/01 : 1.3 : CS
 DM-ID : SIPNG-DM-0060-CN : 2009/07/01 : creation

 FIN-HISTORIQUE
-->
<PLUGIN_CONFIGURATION xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas_plugins.xsd">
	<fileNamePattern>(EXT_TM__DRVFOS)(([0-9]{8}_[0-9]{6})_00000000_[0-9]{8})(_([0-9]{8}_[0-9]{6})_([0-9]{8}_[0-9]{6}).N1)</fileNamePattern>
	<compositeAttribute>
		<name>TIME_PERIOD</name>
		<order>1</order>
		<attributeFromName>
			<groupNumber>5</groupNumber>
			<specification>
				<name>START_DATE</name>
				<valueType>DATE_TIME</valueType>
				<formatRead>yyyyMMdd_HHmmss</formatRead>
			</specification>
		</attributeFromName>
		<attributeFromName>
			<groupNumber>6</groupNumber>
			<specification>
				<name>STOP_DATE</name>
				<valueType>DATE_TIME</valueType>
				<formatRead>yyyyMMdd_HHmmss</formatRead>
			</specification>
		</attributeFromName>
	</compositeAttribute>
	<compositeAttribute>
		<name>CYCLE_RANGE</name>
		<order>5</order>
		<translatedAttributeFromCycleFile>
			<otherAttributeName>START_DATE</otherAttributeName>
			<specification>
				<name>CYCLE_MIN</name>
				<valueType>INTEGER</valueType>
			</specification>
		</translatedAttributeFromCycleFile>
		<translatedAttributeFromCycleFile>
			<otherAttributeName>STOP_DATE</otherAttributeName>
			<specification>
				<name>CYCLE_MAX</name>
				<valueType>INTEGER</valueType>
			</specification>
		</translatedAttributeFromCycleFile>
	</compositeAttribute>
	<attributeFromName>
		<groupNumber>1</groupNumber>
		<groupNumber>4</groupNumber>
		<specification>
			<name>RADICAL</name>
			<valueType>STRING</valueType>
			<order>3</order>
		</specification>
	</attributeFromName>
	<attributeFromName>
		<groupNumber>3</groupNumber>
		<specification>
			<name>FILE_CREATION_DATE</name>
			<valueType>DATE_TIME</valueType>
			<order>4</order>
			<formatRead>yyyyMMdd_HHmmss</formatRead>
		</specification>
	</attributeFromName>
</PLUGIN_CONFIGURATION>
