=== RegardsOss/regards-backend/rs-dam/models/models-domain/src/main/resources/model_V1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- Model root element -->
	<xs:element name="model">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name" />
				<xs:element ref="description" minOccurs="0" />
				<xs:element ref="version" minOccurs="0" />
				<!-- Define model types -->
				<xs:element name="type">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="COLLECTION" />
							<xs:enumeration value="DATA" />
							<xs:enumeration value="DATASET" />
							<xs:enumeration value="DOCUMENT" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element ref="attribute" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="fragment" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- Fragment root element -->
	<xs:element name="fragment">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name" />
				<xs:element ref="description" minOccurs="0" />
				<xs:element ref="version" minOccurs="0" />
				<xs:element ref="attribute" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="ref" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<!-- Define name -->
	<xs:element name="name">
		<xs:simpleType>
			<xs:restriction base="xs:token">
				<xs:pattern value="[0-9a-zA-Z_]{3,32}" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<!-- Define description -->
	<xs:element name="description">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:whiteSpace value="preserve" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<!-- Define description -->
	<xs:element name="version" type="xs:string" />

	<!-- Define attribute -->
	<xs:element name="attribute">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name" />
				<xs:element ref="description" minOccurs="0" />
				<xs:element ref="type" />
				<xs:element name="defaultValue" type="xs:string"
					minOccurs="0" />
				<xs:element ref="restriction" minOccurs="0" />
				<!-- For fragment creation, this element is not used and is skipped silently. -->
				<xs:element ref="computationMode" minOccurs="0" />
				<!-- Custom attribute properties -->
				<xs:element ref="property" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="alterable" type="xs:boolean"
				default="false" />
			<xs:attribute name="optional" type="xs:boolean" default="false" />
			<xs:attribute name="queryable" type="xs:boolean"
				default="false" />
			<xs:attribute name="facetable" type="xs:boolean"
				default="false" />
			<xs:attribute name="group" type="xs:string" />
			<xs:attribute name="ref" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<!-- Define attribute types -->
	<xs:element name="type">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="restrictionType">
					<xs:attribute name="unit" type="xs:string" default="unitless" />
					<xs:attribute name="precision" type="xs:integer" />
					<xs:attribute name="arraysize" type="xs:integer"></xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>


	<!-- All types -->
	<xs:simpleType name="restrictionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="BOOLEAN" />
			<xs:enumeration value="DATE_ARRAY" />
			<xs:enumeration value="DATE_INTERVAL" />
			<xs:enumeration value="DATE_ISO8601" />
			<xs:enumeration value="ENUMERATION" />
			<xs:enumeration value="DOUBLE" />
			<xs:enumeration value="DOUBLE_ARRAY" />
			<xs:enumeration value="DOUBLE_INTERVAL" />
			<xs:enumeration value="GEOMETRY" />
			<xs:enumeration value="INTEGER" />
			<xs:enumeration value="INTEGER_ARRAY" />
			<xs:enumeration value="INTEGER_INTERVAL" />
			<xs:enumeration value="STRING" />
			<xs:enumeration value="STRING_ARRAY" />
			<xs:enumeration value="URL" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Enumeration restriction -->
	<xs:element name="enumeration">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="value" type="xs:string" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- Pattern restriction -->
	<xs:element name="pattern">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:whiteSpace value="preserve" />
				<xs:minLength value="1" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<!-- Integer range restriction -->
	<xs:element name="integer_range">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="min">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:integer">
								<xs:attribute name="excluded" type="xs:boolean"
									default="false" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="max">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:integer">
								<xs:attribute name="excluded" type="xs:boolean"
									default="false" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- Double range restriction -->
	<xs:element name="double_range">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="min">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:double">
								<xs:attribute name="excluded" type="xs:boolean"
									default="false" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="max">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:double">
								<xs:attribute name="excluded" type="xs:boolean"
									default="false" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- Define restriction -->
	<xs:element name="restriction">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="enumeration" />
				<xs:element ref="pattern" />
				<xs:element ref="integer_range" />
				<xs:element ref="double_range" />
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<!-- Define computation modes -->
	<xs:element name="computationMode" default="GIVEN">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="GIVEN" />
				<xs:enumeration value="FROM_DESCENDANTS" />
				<xs:enumeration value="CUSTOM" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<!-- Custom attribute properties -->
	<xs:element name="property">
		<xs:complexType>
			<xs:attribute name="key" type="xs:string" use="required" />
			<xs:attribute name="value" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

</xs:schema>

=== RegardsOss/regards-backend/rs-dam/entities/entities-plugin/src/test/resources/datasetModelSize.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../../models/models-domain/src/main/resources/model_V1.0.xsd">
	<name>datasetModel</name>
	<description>et une petite description parce que je le vaut bien</description>
	<version>Version</version>
	<type>DATASET</type>
	<attribute>
		<name>sizeInteger</name>
		<type>INTEGER</type>
		<computationMode>COMPUTED</computationMode>
		<configurationLabel>SumIntegerTestConf</configurationLabel>
	</attribute>
	<attribute>
		<name>sizeLong</name>
		<type>LONG</type>
		<computationMode>COMPUTED</computationMode>
		<configurationLabel>SumLongTestConf</configurationLabel>
	</attribute>
</model>

=== RegardsOss/regards-backend/rs-catalog/search/search-rest/src/test/resources/fr/cnes/regards/modules/search/rest/engine/data_planet.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="model_V1.0.xsd">
	<name>planet</name>
	<type>DATA</type>
	<attribute>
		<label>Planet name</label>
		<name>planet</name>
		<type>STRING</type>
	</attribute>
	<attribute>
		<label>Start date</label>
		<name>startDate</name>
		<type>DATE_ISO8601</type>
	</attribute>
	<attribute>
		<label>Stop date</label>
		<name>stopDate</name>
		<type>DATE_ISO8601</type>
	</attribute>
	<attribute>
		<label>Planet type</label>
		<name>planet_type</name>
		<type>STRING</type>
		<restriction>
			<enumeration>
				<value>Gas giant</value>
				<value>Ice giant</value>
				<value>Telluric</value>
			</enumeration>
		</restriction>
	</attribute>
</model>

=== RegardsOss/regards-backend/rs-dam/models/models-domain/src/main/resources/cdpp/collection/CDDP_CONTACT_MODEL.xml
<?xml version="1.0" encoding="UTF-8"?>
<model 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../model_V1.0.xsd">
	<name>CDDP_CONTACT_MODEL</name>
	<description>Description du point de contact auquel se rapporte un jeu CDPP</description>
	<version>1</version>
	<type>COLLECTION</type>
    <attribute>
        <label>Nom du contact</label>
        <name>NAME</name>
        <description>Nom du point de contact pour le jeu de donnees</description>
        <type>STRING</type>
        <restriction>
            <pattern>/^.{1,100}$/</pattern>
        </restriction>
    </attribute>
    <attribute>
        <label>Email du contact</label>
        <name>EMAIL</name>
        <description>Email du point de contact pour le jeu de donnees</description>
        <type>STRING</type>
        <restriction>
            <pattern>/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i</pattern>
        </restriction>
    </attribute>
</model>

=== RegardsOss/regards-backend/rs-fem/feature/feature-rest/src/test/resources/fr/cnes/regards/modules/feature/rest/feature_model_01.xml
<?xml version="1.0" encoding="UTF-8" ?>
<model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="model_V1.0.xsd">
    <name>FEATURE01</name>
    <description>Test model</description>
    <version>0.0.1</version>
    <type>DATA</type>
    <attribute alterable="false">
        <label>Data type</label>
        <name>data_type</name>
        <type>STRING</type>
        <restriction>
            <enumeration>
                <value>TYPE01</value>
                <value>TYPE02</value>
                <value>TYPE03</value>
            </enumeration>
        </restriction>
    </attribute>
    <attribute optional="true">
        <label>Label</label>
        <name>label</name>
        <type>STRING</type>
        <restriction>
            <pattern>^.*$</pattern>
        </restriction>
    </attribute>
    <!-- File characterization -->
    <fragment>
        <name>file_characterization</name>
        <attribute>
            <label>Validity flag</label>
            <name>valid</name>
            <type>BOOLEAN</type>
        </attribute>
        <attribute optional="true">
            <label>Invalidation date</label>
            <name>invalidation_date</name>
            <type>DATE_ISO8601</type>
        </attribute>
    </fragment>
</model>
