=== RegardsOss/regards-backend/rs-dam/models/models-domain/src/main/resources/model_V1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- Model root element -->
	<xs:element name="model">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name" />
				<xs:element ref="description" minOccurs="0" />
				<xs:element ref="version" minOccurs="0" />
				<!-- Define model types -->
				<xs:element name="type">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="COLLECTION" />
							<xs:enumeration value="DATA" />
							<xs:enumeration value="DATASET" />
							<xs:enumeration value="DOCUMENT" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element ref="attribute" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="fragment" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- Fragment root element -->
	<xs:element name="fragment">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name" />
				<xs:element ref="description" minOccurs="0" />
				<xs:element ref="version" minOccurs="0" />
				<xs:element ref="attribute" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="ref" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<!-- Define name -->
	<xs:element name="name">
		<xs:simpleType>
			<xs:restriction base="xs:token">
				<xs:pattern value="[0-9a-zA-Z_]{3,32}" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<!-- Define description -->
	<xs:element name="description">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:whiteSpace value="preserve" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<!-- Define description -->
	<xs:element name="version" type="xs:string" />

	<!-- Define attribute -->
	<xs:element name="attribute">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name" />
				<xs:element ref="description" minOccurs="0" />
				<xs:element ref="type" />
				<xs:element name="defaultValue" type="xs:string"
					minOccurs="0" />
				<xs:element ref="restriction" minOccurs="0" />
				<!-- For fragment creation, this element is not used and is skipped silently. -->
				<xs:element ref="computationMode" minOccurs="0" />
				<!-- Custom attribute properties -->
				<xs:element ref="property" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="alterable" type="xs:boolean"
				default="false" />
			<xs:attribute name="optional" type="xs:boolean" default="false" />
			<xs:attribute name="queryable" type="xs:boolean"
				default="false" />
			<xs:attribute name="facetable" type="xs:boolean"
				default="false" />
			<xs:attribute name="group" type="xs:string" />
			<xs:attribute name="ref" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<!-- Define attribute types -->
	<xs:element name="type">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="restrictionType">
					<xs:attribute name="unit" type="xs:string" default="unitless" />
					<xs:attribute name="precision" type="xs:integer" />
					<xs:attribute name="arraysize" type="xs:integer"></xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>


	<!-- All types -->
	<xs:simpleType name="restrictionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="BOOLEAN" />
			<xs:enumeration value="DATE_ARRAY" />
			<xs:enumeration value="DATE_INTERVAL" />
			<xs:enumeration value="DATE_ISO8601" />
			<xs:enumeration value="ENUMERATION" />
			<xs:enumeration value="DOUBLE" />
			<xs:enumeration value="DOUBLE_ARRAY" />
			<xs:enumeration value="DOUBLE_INTERVAL" />
			<xs:enumeration value="GEOMETRY" />
			<xs:enumeration value="INTEGER" />
			<xs:enumeration value="INTEGER_ARRAY" />
			<xs:enumeration value="INTEGER_INTERVAL" />
			<xs:enumeration value="STRING" />
			<xs:enumeration value="STRING_ARRAY" />
			<xs:enumeration value="URL" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Enumeration restriction -->
	<xs:element name="enumeration">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="value" type="xs:string" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- Pattern restriction -->
	<xs:element name="pattern">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:whiteSpace value="preserve" />
				<xs:minLength value="1" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<!-- Integer range restriction -->
	<xs:element name="integer_range">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="min">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:integer">
								<xs:attribute name="excluded" type="xs:boolean"
									default="false" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="max">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:integer">
								<xs:attribute name="excluded" type="xs:boolean"
									default="false" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- Double range restriction -->
	<xs:element name="double_range">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="min">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:double">
								<xs:attribute name="excluded" type="xs:boolean"
									default="false" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="max">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:double">
								<xs:attribute name="excluded" type="xs:boolean"
									default="false" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- Define restriction -->
	<xs:element name="restriction">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="enumeration" />
				<xs:element ref="pattern" />
				<xs:element ref="integer_range" />
				<xs:element ref="double_range" />
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<!-- Define computation modes -->
	<xs:element name="computationMode" default="GIVEN">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="GIVEN" />
				<xs:enumeration value="FROM_DESCENDANTS" />
				<xs:enumeration value="CUSTOM" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<!-- Custom attribute properties -->
	<xs:element name="property">
		<xs:complexType>
			<xs:attribute name="key" type="xs:string" use="required" />
			<xs:attribute name="value" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

</xs:schema>

=== RegardsOss/regards-backend/rs-dam/dam/dam-rest/src/test/resources/fragment_it.xml
<?xml version="1.0" encoding="UTF-8"?>
<fragment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../models-domain/src/main/resources/model_V1.0.xsd">
	<name>IMPORT_FRAGMENT</name>
	<description>Imported fragment from integration test</description>
	<attribute alterable="false" optional="true">
		<label>forTests</label>
		<name>IT_BOOLEAN</name>
		<type>BOOLEAN</type>
	</attribute>
	<attribute alterable="false" optional="false">
		<label>forTests</label>
		<name>IT_STRING</name>
		<type>STRING</type>
		<restriction>
			<enumeration>
				<value>junit</value>
				<value>testng</value>
				<value>selenium</value>
			</enumeration>
		</restriction>
	</attribute>
</fragment>

=== RegardsOss/regards-backend/rs-dam/entities/entities-service/src/test/resources/datasetModelCount.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../../models/models-domain/src/main/resources/model_V1.0.xsd">
	<name>datasetModel</name>
	<description>et une petite description parce que je le vaut bien</description>
	<version>Version</version>
	<type>DATASET</type>
	<attribute>
		<name>count</name>
		<type>LONG</type>
		<computationMode>COMPUTED</computationMode>
		<configurationLabel>CountElementTestConf</configurationLabel>
	</attribute>
</model>

=== RegardsOss/regards-backend/rs-dam/entities/entities-rest/src/test/resources/simple-model.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../../models/models-domain/src/main/resources/model_V1.0.xsd">
	<name>MISSION</name>
	<description>Sample mission</description>
	<type>COLLECTION</type>
	<attribute>
		<label>forTests</label>
		<name>reference</name>
		<type>STRING</type>
	</attribute>
</model>

=== RegardsOss/regards-backend/rs-dam/models/models-domain/src/main/resources/cdpp/dataset/CDDP_DATASET_MODEL.xml
<?xml version="1.0" encoding="UTF-8"?>
<model 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../model_V1.0.xsd">
	<name>CDDP_DATASET_MODEL</name>
	<description>Description d'un jeu de données pour le CDPP</description>
	<version>1</version>
	<type>DATASET</type>
	<attribute>
		<label>Nom (en anglais)</label>
		<name>LABEL</name>
		<description>Nom (en anglais) d'une entité (jeu,table,collection) vue sur l'IHM</description>
		<type>STRING</type>
        <restriction>
            <pattern>/^.{1,80}$/</pattern>
        </restriction>
	</attribute>
	<attribute>
		<label>Taille</label>
		<name>FILE_FORMAT</name>
		<description>Type de format des fichiers du jeu de données</description>
		<type>STRING</type>
		<restriction>
			<enumeration>
				<value>ASCII</value>
				<value>CDF</value>
				<value>CDPP</value>
				<value>CEF</value>
				<value>GIF</value>
				<value>NATIVE</value>
				<value>PDF</value>
				<value>PNG</value>
				<value>POSTSCRIPT</value>
			</enumeration>
		</restriction>
	</attribute>
	<attribute>
		<label>Niveau de traitement</label>
		<name>PROCESSING_LEVEL</name>
		<description>Niveau de traitement effectué sur les données</description>
		<type>STRING</type>
		<restriction>
			<enumeration>
				<value>AUXILIARY</value>
				<value>CALIBRATED</value>
				<value>DERIVED</value>
				<value>RAW</value>
				<value>UNCALIBRATED</value>
			</enumeration>
		</restriction>
	</attribute>
    <attribute>
        <label>Date et temps debut</label>
        <name>START_DATE</name>
        <description>Date et temps debut</description>
        <type>DATE_ISO8601</type>
        <computation>
            <label>CdppDatasetStartDate</label>
            <min_compute parameterAttributeFragmentName="TIME_PERIOD" parameterAttributeName="START_DATE" />
        </computation>
    </attribute>
    <attribute>
        <label>Date et temps fin</label>
        <name>STOP_DATE</name>
        <description>Date et temps fin</description>
        <type>DATE_ISO8601</type>
        <computation>
            <label>CdppDatasetStopDate</label>
            <min_compute parameterAttributeFragmentName="TIME_PERIOD" parameterAttributeName="STOP_DATE" />
        </computation>
    </attribute>
    <attribute>
        <label>Nombre total d'objets</label>
        <name>NB_OBJECTS</name>
        <description>Nombre total d'objets</description>
        <type>INTEGER</type>
        <computation>
            <label>CdppDatasetNbObjects</label>
            <count/>
        </computation>
    </attribute>
    <attribute>
        <label>Taille totale</label>
        <name>TOTAL_SIZE</name>
        <description>Taille totale des objets</description>
        <type>INTEGER</type>
        <computation>
            <label>CdppDatasetTotalSize</label>
            <sum_compute parameterAttributeName="FILE_SIZE" />
        </computation>
    </attribute>
	<fragment>
		<name>PHYSICAL_PARAMETER</name>
		<description>Propriété physique de l'observation mesurée ou derivée</description>
		<version>1</version>
		<attribute>
			<label>Type d'entite</label>
			<name>ENTITY</name>
			<description>Type d'entité dont la propriété est mesurée</description>
			<type>STRING</type>
            <restriction>
                <enumeration>
                    <value>AEROSOL</value>
                    <value>ALPHA</value>
                    <value>DUST</value>
                    <value>ELECTRIC_FIELD</value>
                    <value>ELECTRON</value>
                    <value>HEAVY_MASSES</value>
                    <value>HELIUM</value>
                    <value>HELIUM+</value>
                    <value>INSTRUMENT</value>
                    <value>IONS</value>
                    <value>ION_CNO</value>
                    <value>LIGHT_MASSES</value>
                    <value>MAGNETIC_FIELD</value>
                    <value>MOLECULE</value>
                    <value>NEUTRAL</value>
                    <value>OBSERVATORY</value>
                    <value>OXYGEN+</value>
                    <value>PARTICLES</value>
                    <value>PHOTON</value>
                    <value>PROTON</value>
                </enumeration>
            </restriction>
		</attribute>
		<attribute>
			<label>Propriété</label>
			<name>PROPERTY</name>
			<description>Propriété d'une entité qui est mesurée</description>
			<type>STRING</type>
            <restriction>
                <enumeration>
                    <value>CHARGE_DENSITY</value>
                    <value>COMPONENT</value>
                    <value>CORRECTED_PARTICLE_COUNT_RATE</value>
                    <value>CURRENT</value>
                    <value>DENSITY</value>
                    <value>DIFFERENTIAL_ENERGY_FLUX</value>
                    <value>DIFFERENTIAL_PARTICLE_FLUX</value>
                    <value>DIRECTION</value>
                    <value>DRIFT_VELOCITY</value>
                    <value>HEAT_FLUX</value>
                    <value>INTEGRAL_PARTICLE_FLUX</value>
                    <value>MAGNITUDE</value>
                    <value>MASS_DENSITY</value>
                    <value>MASS_FLUX</value>
                    <value>NUMBER_DENSITY</value>
                    <value>PARTICLE_ENERGY_FLUX</value>
                    <value>PARTICLE_PHASE_SPACE_DENSITY</value>
                    <value>PHASE</value>
                    <value>PHASE_DIFFERENCE</value>
                    <value>PLASMA_FREQUENCY</value>
                    <value>POTENTIAL</value>
                    <value>PRESSURE</value>
                    <value>PRESSURE_TENSOR</value>
                    <value>PROBE_POTENTIAL</value>
                    <value>RAW_PARTICLE_COUNTS</value>
                    <value>RAW_PARTICLE_COUNT_RATE</value>
                    <value>RESONANCE_FREQUENCY</value>
                    <value>SPEED</value>
                    <value>STATUS</value>
                    <value>TEMPERATURE</value>
                    <value>TIME_OF_FLIGHT</value>
                    <value>TOTAL_PARTICLE_FLUX</value>
                    <value>VECTOR</value>
                    <value>VECTOR_MASS_FLUX</value>
                    <value>VELOCITY</value>
                </enumeration>
            </restriction>
        </attribute>
		<attribute>
			<label>Fluctuations</label>
			<name>FLUCTUATIONS</name>
			<description>Fluctuations temporelles d'une propriété mesurée pour un type d'entité ou informations supplémentaires</description>
			<type>STRING</type>
            <restriction>
                <enumeration>
                    <value>BISPECTRUM</value>
                    <value>CORRELATION</value>
                    <value>COVARIANCE</value>
                    <value>CROSS_CORRELATION</value>
                    <value>FOURIER_SPECTRUM</value>
                    <value>FOURIER_CROSS_POWER_SPECTRUM</value>
                    <value>FOURIER_CROSS_SPECTRUM</value>
                    <value>FOURIER_POWER_SPECTRUM</value>
                    <value>MEAN_SQUARE_LEVEL</value>
                    <value>POYNTING_VECTOR</value>
                    <value>POLARISATION</value>
                    <value>RATIO</value>
                    <value>STOKES_PARAMETERS</value>
                    <value>VARIANCE_ESTIMATOR</value>
                    <value>WAVEFORM</value>
                    <value>WAVELET_SPECTRUM</value>
                    <value>WAVELET_CROSS_SPECTRUM</value>
                    <value>WAVELET_POWER_SPECTRUM</value>
                    <value>WAVELET_CROSS_POWER_SPECTRUM</value>
                </enumeration>
            </restriction>
		</attribute>
        <attribute>
            <label>Composé</label>
            <name>COMPOUND</name>
            <description>Composé: indiquant qu'un paramètre est derivé d'autres paramètres observés</description>
            <type>STRING</type>
            <restriction>
                <enumeration>
                    <value>ALFVEN_VELOCITY</value>
                    <value>PLASMA_BETA</value>
                    <value>DERIVED</value>
                </enumeration>
            </restriction>
        </attribute>
	</fragment>
    <fragment>
        <name>TEMPORAL_EXTRACTION_DEFINITION</name>
        <description>Informations relatives a l'extraction temporelle</description>
        <version>1</version>
        <attribute>
            <label>Type de date</label>
            <name>DATE_TYPE</name>
            <description>Type de codage du champ date dans un fichier</description>
            <type>STRING</type>
            <restriction>
                <enumeration>
                    <value>CCSDS_ASCII</value>
                    <value>CCSDS_BINARY</value>
                    <value>CDPP_ASCII</value>
                    <value>CDPP_BINARY</value>
                </enumeration>
            </restriction>
        </attribute>
        <attribute>
            <label>Type du fichier</label>
            <name>FILE_TYPE</name>
            <description>Type (structure,...) du fichier</description>
            <type>STRING</type>
            <restriction>
                <enumeration>
                    <value>FIXED_RECORD</value>
                    <value>VARIABLE_ASCII_RECORD</value>
                    <value>VARIABLE_BINARY_RECORD</value>
                </enumeration>
            </restriction>
        </attribute>
        <attribute>
            <label>Taille de l'enregistrement</label>
            <name>RECORD_LENGTH</name>
            <description>Nombre d'octets d'un enregistrement de taille fixe. Obligatoire pour les enregistrements de taille fixe</description>
            <type>INTEGER</type>
        </attribute>
        <attribute>
            <label>Taille de l'enregistrement</label>
            <name>DATE_POSITION</name>
            <description>Rang du 1er bit d'un enregistrement (bit gauche)</description>
            <type>INTEGER</type>
        </attribute>
    </fragment>
</model>

=== RegardsOss/regards-backend/rs-dam/crawler/crawler-service/src/test/resources/validation/models/validationDataModel2.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../../../../../../../models/models-domain/src/main/resources/model_V1.0.xsd">
    <name>VALIDATION_DATA_MODEL_2</name>
    <description>validation data model with geometries</description>
    <version>1</version>
    <type>DATA</type>
    <attribute>
        <label>pays</label>
        <name>country</name>
        <type>STRING</type>
    </attribute>
    <attribute>
        <label>superficie</label>
        <name>area</name>
        <type>DOUBLE</type>
    </attribute>
</model>

=== RegardsOss/regards-backend/rs-dam/dam/dam-service/src/test/resources/dataModelSize.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../models-domain/src/main/resources/model_V1.0.xsd">
	<name>dataModel</name>
	<description>et une petite description parce que je le vaut bien</description>
	<version>Version</version>
	<type>DATA</type>
	<attribute>
		<label>forTests</label>
		<name>sizeInteger</name>
		<type>INTEGER</type>
	</attribute>
	<attribute>
		<label>forTests</label>
		<name>sizeLong</name>
		<type>LONG</type>
	</attribute>
</model>

=== RegardsOss/regards-backend/rs-dam/models/models-rest/src/test/resources/model_it.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="model_V1.0.xsd">
	<name>sample</name>
	<description>Sample mission</description>
	<type>COLLECTION</type>
	<attribute alterable="false" optional="true" queryable="false"
		facetable="false">
		<name>att_string</name>
		<type>STRING</type>
		<computationMode>GIVEN</computationMode>
	</attribute>
	<fragment>
		<name>GEO</name>
		<description>Geographic information</description>
		<attribute alterable="false" optional="false" queryable="false"
			facetable="false">
			<name>CRS</name>
			<type>STRING</type>
			<restriction>
				<enumeration>
					<value>Earth</value>
					<value>Mars</value>
					<value>Venus</value>
				</enumeration>
			</restriction>
			<computationMode>GIVEN</computationMode>
		</attribute>
		<attribute alterable="false" optional="false" queryable="false"
			facetable="false">
			<name>GEOMETRY</name>
			<type>GEOMETRY</type>
			<computationMode>GIVEN</computationMode>
		</attribute>
	</fragment>
	<fragment>
		<name>Contact</name>
		<description>Contact information</description>
		<attribute alterable="true" optional="true" queryable="true"
			facetable="true">
			<name>Phone</name>
			<type>STRING</type>
			<restriction>
				<pattern>[0-9 ]{10}</pattern>
			</restriction>
			<computationMode>FROM_DESCENDANTS</computationMode>
		</attribute>
	</fragment>
</model>

=== RegardsOss/regards-backend/rs-dam/dam/dam-domain/src/test/resources/model.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../main/resources/model_V1.0.xsd">
	<name>sample</name>
	<description>Sample mission</description>
	<type>COLLECTION</type>
	<attribute alterable="false" optional="false" queryable="false"
		facetable="false">
		<name>att_string</name>
		<type>STRING</type>
		<computationMode>GIVEN</computationMode>
	</attribute>
	<attribute alterable="false" optional="false" queryable="false"
		facetable="false">
		<name>att_boolean</name>
		<type>BOOLEAN</type>
		<computationMode>GIVEN</computationMode>
	</attribute>
	<attribute>
		<name>floatnb</name>
		<description>one floating number</description>
		<type>DOUBLE</type>
		<restriction>
			<double_range>
				<min excluded="false">10</min>
				<max excluded="false">20</max>
			</double_range>
		</restriction>
		<computationMode>GIVEN</computationMode>
	</attribute>
	<attribute>
		<name>integer_range</name>
		<description>an integer range</description>
		<type>DOUBLE</type>
		<restriction>
			<integer_range>
				<min excluded="true">20</min>
				<max>30</max>
			</integer_range>
		</restriction>
		<computationMode>GIVEN</computationMode>
	</attribute>
	<fragment>
		<name>GEO</name>
		<description>Geographic information</description>
		<attribute alterable="false" optional="false" queryable="false"
			facetable="false">
			<name>CRS</name>
			<type>STRING</type>
			<restriction>
				<enumeration>
					<value>Earth</value>
					<value>Mars</value>
					<value>Venus</value>
				</enumeration>
			</restriction>
			<computationMode>GIVEN</computationMode>
		</attribute>
		<attribute alterable="false" optional="false" queryable="false"
			facetable="false">
			<name>GEOMETRY</name>
			<type>GEOMETRY</type>
			<computationMode>GIVEN</computationMode>
		</attribute>
	</fragment>
	<fragment>
		<name>Contact</name>
		<description>Contact information</description>
		<attribute alterable="false" optional="false" queryable="false"
			facetable="false">
			<name>Phone</name>
			<type>STRING</type>
			<restriction>
				<pattern>[0-9 ]{10}</pattern>
			</restriction>
			<computationMode>GIVEN</computationMode>
		</attribute>
	</fragment>
</model>
